### ISSUE TITLE
Extended combat sim for T4

### ISSUE THREAD

**Issue by achenchen1** [kirilloid/travian#4]
The extended combat calculator for T4 (_not_ the old T4) is a little bugged with hero items; when you add a small shield/tier 1 weapon the numbers totally blow up. Additionally, the values for some of the combat strengths are wrong; tier 1 items have 250 combat strength, light breastplate only has 250 combat strength, light segmented only has 125 combat strength, might have some more changes. 

On line 1458 in warsim2.php

Also, adding items completely fucks up the total combat strength for whatever reason. Calculations seem about right, but number looks weird.

**Comment by kirilloid** [comment]
Is it fixed now?

**Comment by achenchen1** [comment]
I do believe so :smile:
