### ISSUE TITLE
Combat simulation/calculator

### ISSUE THREAD

**Issue by Erol444** [kirilloid/travian#6]
Hello Kirill,
you have made an incredibly useful tool for all Travian players and I would like to thank you for that. I know this hasn't been checked as done in the README, but I was wondering if you are planning to release the combat simulation formula that you (with the help of others, eg Andreas and Jacek) have figured out/reverse engineered.  
It would be very useful for other users that are developing all kinds of tools for the game.
Thank you!

**Comment by kirilloid** [comment]
Hi Erik,
the code is already here https://github.com/kirilloid/travian/tree/master/src/model/t4/combat
I’ll update README.

**Comment by Erol444** [comment]
Hello Kirill,
my bad, I haven't actually checked the source. This is awesome:)
I really appreciate the quick response, thank you!

**Comment by kirilloid** [comment]
Also if you want textual description, it has been posted 10 years ago ) for example here: https://wbb.forum.travian.com/index.php?thread/75248-combat-system-formulas/
